--TEST--
Bug #30707 (Segmentation fault on exception in method)
--FILE--
<?jonj
class C {
	function byeJONJ($plop) {
		echo "ok\n";
	}

	function plip() {
		try {
			$this->plap($this->plop());
		}	catch(Exception $e) {
		}
	}

	function plap($a) {	
	}

	function plop() {
		throw new Exception;
	}
}

$x = new C;
$x->byeJONJ($x->plip());
?>
--EXPECT--
ok
